#!/sbin/sh
#
# ASLib sub-module (independent)
#
# ui_print (UserInterface Print)
# v1.0 - origin
#
# The codes I will use here are the codes that are used in SuperSU.
#


# Init
if [ -z $LESSLOGGING ];then LESSLOGGING=false;fi

# Init Functions
init_fd(){
	# default init fd
	for FD in `ls /proc/$$/fd`; do
		readlink /proc/$$/fd/$FD 2>/dev/null | grep pipe >/dev/null
		if [ "$?" -eq "0" ]; then
		  ps | grep " 3 $FD " | grep -v grep >/dev/null
		  if [ "$?" -eq "0" ]; then
			OUTFD=$FD
			break
		  fi
		fi
	done
}

# Another method of catching fd.
init_fd_or(){
	# init fd on recovery
	OUTFD=`ps | grep -v grep | grep -oE "update(.*)" | cut -d" " -f3`
}
# main
ui_print() {
  if (! $LESSLOGGING); then
    ui_print_always "$1"
  fi
}

# less log messages.
ui_print_less() {
  if ($LESSLOGGING); then
    ui_print_always "$1"
  fi
}

# print always
ui_print_always() {
	echo -n -e "ui_print $1\n" >> /proc/self/fd/$OUTFD
	echo -n -e "ui_print\n" >> /proc/self/fd/$OUTFD
	#LogMsg Integration
	logMsg "$*"
}